import { Quicksand } from "next/font/google";
import "../(layout)/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const quickSand = Quicksand({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" dark">
      <body className={`${quickSand.className} bg-background text-foreground`}>
        {children}
      </body>
    </html>
  );
}
