import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/providers";
import { auth } from "@/auth";
import { Navbar } from "@/components/navbar";
const quickSand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user;

  return (
    <html lang="en">
      <body className={`${quickSand.className} bg-background text-foreground`}>
        <SessionProvider>
          <ThemeProvider
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            attribute="class"
          >
            <div className="px-4 max-w-5xl mx-auto">
              <Navbar user={user} />
              {children}
            </div>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
