import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import "./prismSyntax.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/providers";
import { Toaster } from "@/components/ui/toaster";
const quickSand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quickSand.className} bg-background text-foreground`}>
        <SessionProvider>
          <ThemeProvider
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            attribute="class"
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
